[workspace]
members = ["server", "ui", "api"]

[[workspace.metadata.leptos]]
name = "wordforge"
bin-package = "wordforge-server"
lib-package = "wordforge-ui"
site-root = "target/site"
style-file = "target/style.css"
assets-dir = "public"
reload-port = 3001
lib-features = ["hydrate"]
