[package]
name = "activitypub-test"
version = "0.1.0"
edition = "2021"

[dependencies]
activitypub_federation = { git = "https://github.com/LemmyNet/activitypub-federation-rust.git", rev = "5a5c015", features = [
  "actix-web",
] }
actix-web = "4.3.0"
async-trait = "0.1.64"
dotenv = "0.15.0"
env_logger = "0.10.0"
reqwest = "0.11.14"
url = { version = "2.3.1", features = ["serde"] }
