[package]
name = "activitypub-test"
version = "0.1.0"
edition = "2021"

[dependencies]
activitypub_federation = { git = "https://github.com/LemmyNet/activitypub-federation-rust.git", rev = "5a5c015", features = [
  "actix-web",
] }
actix-web = "4.3.0"
anyhow = "1.0.69"
async-trait = "0.1.64"
chrono = { version = "0.4.23", features = ["serde"] }
diesel = { version = "2.0.3", features = ["postgres", "r2d2"] }
diesel_migrations = { version = "2.0.0", features = ["postgres"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
rand = { version = "0.8.5", features = ["serde"] }
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
url = { version = "2.3.1", features = ["serde"] }
