services:
  postgresql:
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    image: docker.io/postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  postgresql:
