services:
  cache:
    command: redis-server /etc/redis/redis.conf
    container_name: redisserver
    image: docker.io/library/redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
      - $PWD/redis.conf:/etc/redis/redis.conf
  postgresql:
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    image: docker.io/postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  postgresql:
  redis-data:
